Fix/add minor version nodejs
lean-delivery/ansible-role-nodejs pull request #9
Opened 2019-04-23 08:18 UTC by avpash43

Added minor version nodejs and updated an existing role by coockiecutter

2019-04-23 08:31 UTC, pavelpikta submitted a review, later dismissed

2019-04-23 08:31 UTC, pavelpikta commented on README.md
> +![Ansible](https://img.shields.io/ansible/role/d/role_id.svg)
replace role_id to 32264

2019-04-23 08:31 UTC, pavelpikta commented on README.md
> +A brief description of the role goes here.
restore previous readme content

2019-04-23 08:31 UTC, pavelpikta commented on meta/main.yml
> +  description: Yet Another Ansible Role From Lean Delivery
restore previous content

2019-04-23 08:31 UTC, pavelpikta commented on molecule/resources/tests/test_default.py
> +def test_hosts_file(host):
restore previous python test

2019-04-24 12:55 UTC, tgadiev requested changes

2019-04-24 12:55 UTC, tgadiev commented on README.md
> +[![Build Status](https://gitlab.com/lean-delivery/ansible-role-nodejs/badges/master/build.svg)](https://gitlab.com/lean-delivery/ansible-role-nodejs)
```suggestion
[![Build Status](https://gitlab.com/lean-delivery/ansible-role-nodejs/badges/master/build.svg)](https://gitlab.com/lean-delivery/ansible-role-nodejs/pipelines)
```

2019-04-24 12:55 UTC, tgadiev commented on .travis.yml
>    - pip install --upgrade ansible==2.5.* docker-py molecule==2.17 pyOpenSSL PyYAML pytest==3.7.4
```suggestion
  - pip install --upgrade ansible==2.7.* docker-py molecule==2.20 pyOpenSSL PyYAML pytest
```

2019-04-24 12:55 UTC, tgadiev commented on molecule/cloud-aws-direct/molecule.yml
> +    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
```suggestion
```

2019-04-24 12:55 UTC, tgadiev commented on molecule/cloud-aws-direct/molecule.yml
> +  env:
```suggestion
```

2019-04-24 12:55 UTC, tgadiev commented on tasks/system/Debian.yml
> +          deb https://deb.nodesource.com/node_{{ nodejs_major_version }}
That should be moved to dedicated variable to be able to override it.

2019-04-24 12:55 UTC, tgadiev commented on tasks/system/RedHat.yml
> +        name: "{{ nodejs_transport }}://rpm.nodesource.com/pub_{{ nodejs_major_version }}\
That should be moved to dedicated variable to be able to override it.

2019-04-24 13:52 UTC, tgadiev approved these changes

2019-04-24 13:54 UTC, merged